-- Capstan Cloud colorscheme for Neovim
-- A warm dark theme with brass accents

return {
  {
    "AstroNvim/astroui",
    ---@type AstroUIOpts
    opts = {
      -- Use astrodark as base, override with Capstan colors
      colorscheme = "astrodark",
      highlights = {
        -- Apply to astrodark theme
        astrodark = {
          -- Base UI
          Normal = { bg = "#1a1917", fg = "#f7f7f5" },
          NormalNC = { bg = "#1a1917", fg = "#b8b5b0" },
          NormalFloat = { bg = "#262422", fg = "#f7f7f5" },
          FloatBorder = { bg = "#262422", fg = "#524f4c" },
          FloatTitle = { bg = "#262422", fg = "#d4a366", bold = true },
          CursorLine = { bg = "#262422" },
          CursorLineNr = { fg = "#d4a366", bold = true },
          LineNr = { fg = "#524f4c" },
          SignColumn = { bg = "#1a1917" },
          Visual = { bg = "#393634" },
          Search = { bg = "#d4a366", fg = "#1a1917" },
          IncSearch = { bg = "#f8ce9b", fg = "#1a1917" },
          CurSearch = { bg = "#f8ce9b", fg = "#1a1917" },
          
          -- Status line
          StatusLine = { bg = "#1a1917", fg = "#f7f7f5" },
          StatusLineNC = { bg = "#1a1917", fg = "#8c8985" },
          WinBar = { bg = "#1a1917", fg = "#f7f7f5" },
          WinBarNC = { bg = "#1a1917", fg = "#8c8985" },
          
          -- Popup menu
          Pmenu = { bg = "#262422", fg = "#f7f7f5" },
          PmenuSel = { bg = "#d4a366", fg = "#1a1917" },
          PmenuSbar = { bg = "#393634" },
          PmenuThumb = { bg = "#524f4c" },
          
          -- Tabs
          TabLine = { bg = "#1a1917", fg = "#8c8985" },
          TabLineSel = { bg = "#d4a366", fg = "#1a1917", bold = true },
          TabLineFill = { bg = "#1a1917" },
          
          -- Splits
          VertSplit = { fg = "#393634" },
          WinSeparator = { fg = "#393634" },
          
          -- Folding
          Folded = { bg = "#262422", fg = "#8c8985" },
          FoldColumn = { bg = "#1a1917", fg = "#524f4c" },
          
          -- Syntax (base)
          Comment = { fg = "#8c8985", italic = true },
          String = { fg = "#52c41a" },
          Character = { fg = "#52c41a" },
          Number = { fg = "#f8ce9b" },
          Float = { fg = "#f8ce9b" },
          Boolean = { fg = "#d4a366" },
          Keyword = { fg = "#d4a366", bold = true },
          Conditional = { fg = "#d4a366", bold = true },
          Repeat = { fg = "#d4a366", bold = true },
          Statement = { fg = "#d4a366" },
          Function = { fg = "#8fa5ae" },
          Identifier = { fg = "#f7f7f5" },
          Type = { fg = "#d4a366" },
          StorageClass = { fg = "#d4a366" },
          Structure = { fg = "#d4a366" },
          Constant = { fg = "#f8ce9b" },
          Operator = { fg = "#b8b5b0" },
          Delimiter = { fg = "#8c8985" },
          Special = { fg = "#f8ce9b" },
          SpecialChar = { fg = "#f8ce9b" },
          PreProc = { fg = "#d4a366" },
          Include = { fg = "#d4a366" },
          Define = { fg = "#d4a366" },
          Macro = { fg = "#f8ce9b" },
          Title = { fg = "#d4a366", bold = true },
          
          -- Diagnostics
          DiagnosticError = { fg = "#ff4d4f" },
          DiagnosticWarn = { fg = "#faad14" },
          DiagnosticInfo = { fg = "#8fa5ae" },
          DiagnosticHint = { fg = "#52c41a" },
          DiagnosticVirtualTextError = { fg = "#ff4d4f", bg = "#2e1a1a" },
          DiagnosticVirtualTextWarn = { fg = "#faad14", bg = "#2e2a1a" },
          DiagnosticVirtualTextInfo = { fg = "#8fa5ae", bg = "#1a2228" },
          DiagnosticVirtualTextHint = { fg = "#52c41a", bg = "#1a2e1a" },
          DiagnosticUnderlineError = { undercurl = true, sp = "#ff4d4f" },
          DiagnosticUnderlineWarn = { undercurl = true, sp = "#faad14" },
          DiagnosticUnderlineInfo = { undercurl = true, sp = "#8fa5ae" },
          DiagnosticUnderlineHint = { undercurl = true, sp = "#52c41a" },
          
          -- Git signs
          GitSignsAdd = { fg = "#52c41a" },
          GitSignsChange = { fg = "#faad14" },
          GitSignsDelete = { fg = "#ff4d4f" },
          
          -- Diff
          DiffAdd = { bg = "#1a2e1a" },
          DiffChange = { bg = "#2e2a1a" },
          DiffDelete = { bg = "#2e1a1a" },
          DiffText = { bg = "#3e3a2a" },
          
          -- Treesitter
          ["@variable"] = { fg = "#f7f7f5" },
          ["@variable.builtin"] = { fg = "#f8ce9b" },
          ["@variable.parameter"] = { fg = "#f7f7f5" },
          ["@variable.member"] = { fg = "#b8b5b0" },
          ["@constant"] = { fg = "#f8ce9b" },
          ["@constant.builtin"] = { fg = "#f8ce9b" },
          ["@module"] = { fg = "#d4a366" },
          ["@label"] = { fg = "#d4a366" },
          ["@string"] = { fg = "#52c41a" },
          ["@string.escape"] = { fg = "#f8ce9b" },
          ["@string.special"] = { fg = "#f8ce9b" },
          ["@character"] = { fg = "#52c41a" },
          ["@number"] = { fg = "#f8ce9b" },
          ["@boolean"] = { fg = "#d4a366" },
          ["@type"] = { fg = "#d4a366" },
          ["@type.builtin"] = { fg = "#d4a366" },
          ["@attribute"] = { fg = "#d4a366" },
          ["@property"] = { fg = "#b8b5b0" },
          ["@function"] = { fg = "#8fa5ae" },
          ["@function.builtin"] = { fg = "#8fa5ae" },
          ["@function.call"] = { fg = "#8fa5ae" },
          ["@function.method"] = { fg = "#8fa5ae" },
          ["@function.method.call"] = { fg = "#8fa5ae" },
          ["@constructor"] = { fg = "#d4a366" },
          ["@keyword"] = { fg = "#d4a366", bold = true },
          ["@keyword.function"] = { fg = "#d4a366", bold = true },
          ["@keyword.operator"] = { fg = "#d4a366" },
          ["@keyword.return"] = { fg = "#d4a366", bold = true },
          ["@keyword.conditional"] = { fg = "#d4a366", bold = true },
          ["@keyword.repeat"] = { fg = "#d4a366", bold = true },
          ["@keyword.import"] = { fg = "#d4a366" },
          ["@operator"] = { fg = "#b8b5b0" },
          ["@punctuation"] = { fg = "#8c8985" },
          ["@punctuation.bracket"] = { fg = "#8c8985" },
          ["@punctuation.delimiter"] = { fg = "#8c8985" },
          ["@punctuation.special"] = { fg = "#f8ce9b" },
          ["@comment"] = { fg = "#8c8985", italic = true },
          ["@tag"] = { fg = "#d4a366" },
          ["@tag.attribute"] = { fg = "#8fa5ae" },
          ["@tag.delimiter"] = { fg = "#8c8985" },
          
          -- LSP semantic tokens
          ["@lsp.type.class"] = { fg = "#d4a366" },
          ["@lsp.type.decorator"] = { fg = "#f8ce9b" },
          ["@lsp.type.enum"] = { fg = "#d4a366" },
          ["@lsp.type.enumMember"] = { fg = "#f8ce9b" },
          ["@lsp.type.function"] = { fg = "#8fa5ae" },
          ["@lsp.type.interface"] = { fg = "#d4a366" },
          ["@lsp.type.macro"] = { fg = "#f8ce9b" },
          ["@lsp.type.method"] = { fg = "#8fa5ae" },
          ["@lsp.type.namespace"] = { fg = "#d4a366" },
          ["@lsp.type.parameter"] = { fg = "#f7f7f5" },
          ["@lsp.type.property"] = { fg = "#b8b5b0" },
          ["@lsp.type.struct"] = { fg = "#d4a366" },
          ["@lsp.type.type"] = { fg = "#d4a366" },
          ["@lsp.type.typeParameter"] = { fg = "#d4a366" },
          ["@lsp.type.variable"] = { fg = "#f7f7f5" },
          
          -- Telescope
          TelescopeBorder = { fg = "#524f4c", bg = "#1a1917" },
          TelescopeNormal = { bg = "#1a1917" },
          TelescopePreviewBorder = { fg = "#524f4c", bg = "#1a1917" },
          TelescopePreviewNormal = { bg = "#1a1917" },
          TelescopePreviewTitle = { fg = "#1a1917", bg = "#52c41a" },
          TelescopePromptBorder = { fg = "#524f4c", bg = "#262422" },
          TelescopePromptNormal = { bg = "#262422" },
          TelescopePromptPrefix = { fg = "#d4a366" },
          TelescopePromptTitle = { fg = "#1a1917", bg = "#d4a366" },
          TelescopeResultsBorder = { fg = "#524f4c", bg = "#1a1917" },
          TelescopeResultsNormal = { bg = "#1a1917" },
          TelescopeResultsTitle = { fg = "#1a1917", bg = "#8fa5ae" },
          TelescopeSelection = { bg = "#262422", fg = "#f7f7f5" },
          TelescopeSelectionCaret = { fg = "#d4a366" },
          TelescopeMatching = { fg = "#d4a366", bold = true },
          
          -- Neo-tree
          NeoTreeNormal = { bg = "#1a1917", fg = "#f7f7f5" },
          NeoTreeNormalNC = { bg = "#1a1917", fg = "#b8b5b0" },
          NeoTreeDirectoryIcon = { fg = "#d4a366" },
          NeoTreeDirectoryName = { fg = "#f7f7f5" },
          NeoTreeRootName = { fg = "#d4a366", bold = true },
          NeoTreeFileName = { fg = "#f7f7f5" },
          NeoTreeFileIcon = { fg = "#8c8985" },
          NeoTreeGitAdded = { fg = "#52c41a" },
          NeoTreeGitDeleted = { fg = "#ff4d4f" },
          NeoTreeGitModified = { fg = "#faad14" },
          NeoTreeGitUntracked = { fg = "#8c8985" },
          NeoTreeIndentMarker = { fg = "#393634" },
          NeoTreeCursorLine = { bg = "#262422" },
          
          -- Which-key
          WhichKey = { fg = "#d4a366" },
          WhichKeyGroup = { fg = "#8fa5ae" },
          WhichKeyDesc = { fg = "#f7f7f5" },
          WhichKeySeparator = { fg = "#524f4c" },
          WhichKeyFloat = { bg = "#262422" },
          WhichKeyBorder = { fg = "#524f4c", bg = "#262422" },
          
          -- Indent blankline
          IblIndent = { fg = "#393634" },
          IblScope = { fg = "#524f4c" },
          
          -- Notify
          NotifyERRORBorder = { fg = "#ff4d4f" },
          NotifyWARNBorder = { fg = "#faad14" },
          NotifyINFOBorder = { fg = "#8fa5ae" },
          NotifyDEBUGBorder = { fg = "#8c8985" },
          NotifyTRACEBorder = { fg = "#b48ead" },
          NotifyERRORIcon = { fg = "#ff4d4f" },
          NotifyWARNIcon = { fg = "#faad14" },
          NotifyINFOIcon = { fg = "#8fa5ae" },
          NotifyDEBUGIcon = { fg = "#8c8985" },
          NotifyTRACEIcon = { fg = "#b48ead" },
          NotifyERRORTitle = { fg = "#ff4d4f" },
          NotifyWARNTitle = { fg = "#faad14" },
          NotifyINFOTitle = { fg = "#8fa5ae" },
          NotifyDEBUGTitle = { fg = "#8c8985" },
          NotifyTRACETitle = { fg = "#b48ead" },
        },
      },
      icons = {
        LSPLoading1 = "⠋",
        LSPLoading2 = "⠙",
        LSPLoading3 = "⠹",
        LSPLoading4 = "⠸",
        LSPLoading5 = "⠼",
        LSPLoading6 = "⠴",
        LSPLoading7 = "⠦",
        LSPLoading8 = "⠧",
        LSPLoading9 = "⠇",
        LSPLoading10 = "⠏",
      },
    },
  },
}
